In [3]:
import numpy as np 

arr = np.array([1,2,3,4,5])
x = arr.copy()
print(x)

[1 2 3 4 5]


In [8]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7])
z = arr.view()
print(arr)
z[0] = 13
print(z)


[1 2 3 4 5 6 7]
[13  2  3  4  5  6  7]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[:4])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[1 2 3 4]
[2 4]
[1 3 5 7]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [24]:
# arrays shape

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # 3 dimentional array with two elements
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# flattening the array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-3) 

print(newarr)

[1 2 3 4 5 6]


In [ ]:
# unknown dimentional array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

In [31]:
# return copy or view 

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [35]:
# reshpaing to any shpape 

# import numpy as np 

# arr = np.array ([1,2,3,4,5,6,7,8,9,10])

# newarr = arr.reshape(3,3)
# print(newarr)


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

# error is raised because it cannot with 8 elements into an 3d array

ValueError: cannot reshape array of size 8 into shape (3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]
