In [8]:
# example 1

# example 2

import numpy as np

array1= np.array([1, 2, 3, 4, 5, 6])

array2= np.array([[1, 2, 3], [4, 5, 6]])

print(array1)
print(array2)




[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [6]:
# example 3
import numpy as np 

z = np.array([1,2,3,'a',5, 8.9])  # integer, float is going to be convereted into string
F = np.array([1,2,3,5, 8.9]) # converted to float
print(F) 

# priority --> string > float > Integer


[1.  2.  3.  5.  8.9]


In [18]:
# example 4

import numpy as np
a = np.linspace(start = 1, stop = 5, endpoint = True, retstep = False)
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
print(a)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [20]:
# example 5

import numpy as np

# np.arange(start, stop, step)
d = np.arange(start =1, stop = 10, step = 2)
print(d)

[1 3 5 7 9]


For 2D Array --> INT datatype
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
For Default Datatype
[1. 1. 1. 1.]
For 1D Array --> String Datatype
['1' '1' '1' '1' '1' '1' '1' '1']


In [33]:

# example 7 

import numpy as np

print("1D array")

a = np.zeros((3,4))
print(a)

b = np.zeros((3,4), int)
print(b)

c = np.zeros((3,4), str)
print(c)

1D array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [37]:
# random function

# example 8

import numpy as np

c = np.random.rand(10)

print(c)


[0.63189251 0.96195134 0.40037358 0.85153936 0.58892274 0.51167644
 0.2903286  0.33590926 0.78211671 0.1166162 ]


In [43]:
# numpy.logspace()

# numpy.logspace(start, stop, num, endpoint, base, dtype)

# num --> number of sample to gernerate
import numpy as np
a = np.logspace(1, 5, num =10, endpoint = True, base = 10.0)
print(a)


[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [ ]:
# timeit
# sys.getsizeof(object)
# it