In [1]:
#python program to calculate square of a number
num = float(input("Enter the Number : "))

square = num * num

print("The Square of a Given Number {0}  = {1}".format(num, square))

Enter the Number : 15
The Square of a Given Number 15.0  = 225.0


In [2]:
print("class")

class


In [3]:
#while loop
i=1
while i<=5:
    print("class")
    i=i+1

class
class
class
class
class


In [4]:
#for loop 
rows=6
for i in range(rows):
    for j in range(i):

        print(i, end='')

    print('')



1
22
333
4444
55555


In [5]:
#for loop 
rows=4

for i in range(rows):
    for j in range(rows):

        print('#', end='')

    print('')


####
####
####
####


In [6]:
import numpy as np

arr=np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


In [7]:
import numpy as np

arr=np.array(42)

print(arr)

42


In [8]:
#1D ARRAY
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [9]:
#2D ARRAY
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#3D ARRAY
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
#ARRAY INDEXING
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr[1])

2


In [12]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr[2]+arr[3])

7


In [13]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('second element of first dimension:',arr[0,1])

second element of first dimension: 2


In [14]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('fifth element of second dimension:',arr[1,4])

fifth element of second dimension: 10


In [15]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


In [16]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[1,1,2])

12


In [17]:
#Negative indexing
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('Last element of second dimension:',arr[1,-1])

Last element of second dimension: 10


In [18]:
#Array slicing
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [19]:
#Array slicing with step
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [20]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [21]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[4::])

[5 6 7]


In [22]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[4::2])

[5 7]


In [23]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]
