# Iterating through arrays

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [11]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [14]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Joining the arrays

In [17]:
import numpy as np

array1 = ([1,2,3,4,5])

array2 = ([6,7,8,9,10])

new_array = np.concatenate((array1,array2))

print(new_array)


[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
import numpy as np 

arr = ([[1,3,4,5], [6,73,26,21]])

arr1 = ([[11,53,54,2], [16,73,16,51]])

new_array = np.concatenate((arr,arr1), axis =1)

print(new_array)

[[ 1  3  4  5 11 53 54  2]
 [ 6 73 26 21 16 73 16 51]]


In [31]:
import numpy as np


arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 2 3]
 [4 5 6]]


In [36]:
# stacking along the rows

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [37]:
# stacking along columns

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [38]:
# stack along height (depth)

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# splitting between the arrays

In [45]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

newarr = np.array_split(arr, 4)

print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10]), array([11, 12, 13])]
[1 2 3 4]
[5 6 7]
[ 8  9 10]
[11 12 13]


In [63]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# searching in the arrays

In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [75]:
# finding the index where the value 7 should be inserted

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [80]:
# searching from right side 

import numpy as np

arr = np.array([6, 7, 8, 9])


x = np.searchsorted(arr, 8, side='right')

print(x)


3


# array sorting 

In [82]:
import numpy as np

arr = np.array(['a', 'b', 'c'])

print(np.sort(arr))


['a' 'b' 'c']


In [83]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = [True, False, True, False]

print(arr[x])

[6 8]
